#!/bin/bash

ask() {
  read -p $'\e[34m'"$1"$'\e[0m' value

  if [ "$value" == "" ]; then
    echo $2
  fi

  echo $value
}

echo '# ==================================================================================================== #'
echo '#                                                                                                      #'
echo '#                                   Installation of new web project                                    #'
echo '#                                                                                                      #'
echo '# ==================================================================================================== #'

echo
echo ' This create a new project with angular and AWS API gateway.'
echo

projectName=$(ask   " Write the name of your project       : [project] " "project")
angularPrefix=$(ask " Choose a prefix for angular          : [app]     " "app")
angularStyle=$(ask  " Choose your style syntax for angular : [scss]    " "scss")

echo $projectName
echo $angularPrefix
echo $angularStyle
